export const Orders = [
  {
    unique_number: 'asd234',
    order_code: 'OD001',
    customer_id: 1,
    user_id: 2,
    delivery_point: 'Ayeduase gate',
    payment: 'full_payment',
    status: 'Pending',
    amount_paid: 200,
    payment_mode: 'Mobile money',
    order_channel: '',
    created_at: new Date(),
  },
  {
    unique_number: 'asd456',
    order_code: 'OD002',
    customer_id: 2,
    user_id: 2,
    delivery_point: 'knust entrance',
    payment: 'half_payment',
    status: 'Pending',
    amount_paid: 150,
    payment_mode: 'Cash',
    order_channel: '',
    created_at: new Date(),
  },
  {
    unique_number: 'asd345',
    order_code: 'OD003',
    customer_id: 3,
    user_id: 1,
    delivery_point: 'Tech junction',
    payment: 'full payment',
    status: 'Delivered',
    amount_paid: 700,
    payment_mode: 'Mobile money',
    order_channel: '',
    created_at: new Date(),
  },
];
