export const Users = [
  {
    name: 'John Jerry',
    email: 'john@gmail.com',
    password: 'John2023',
    phone_number: '+233578230846',
    role_id: 1,
    verified: true,
    pwd_expired_at: new Date(),
    pwd_code: 'AP001',
    created_at: new Date(),
  },
  {
    name: 'Ben Martin',
    email: 'bmartin@gmail.com',
    password: 'Martin2023',
    phone_number: '+2332490745276',
    role_id: 2,
    verified: false,
    pwd_expired_at: new Date(),
    pwd_code: 'AP002',
    created_at: new Date(),
  },
  {
    name: 'Emmanuel Kode',
    email: 'kode@gmail.com',
    password: 'Kode2023',
    phone_number: '+2338574785845',
    role_id: 3,
    verified: true,
    pwd_expired_at: new Date(),
    pwd_code: 'AP002',
    created_at: new Date(),
  },
  {
    name: 'Alfred Ayertey',
    email: 'alfred@gmail.com',
    password: 'Alfred2023',
    phone_number: '+2332494595276',
    role_id: 4,
    verified: false,
    pwd_expired_at: new Date(),
    pwd_code: 'AP002',
    created_at: new Date(),
  },
];
